require:
  - rubocop-performance
  - rubocop-md
  - rubocop-rake
  - rubocop-thread_safety

AllCops:
  Exclude:
    - lib/pseudo_legal_move_tablebase/puchi_shogi.rb
    - test.rb

  NewCops: enable

  TargetRubyVersion: 2.7

Style/StringLiterals:
  EnforcedStyle: double_quotes

# We do not need to support Ruby 1.9, so this is good to use.
Style/SymbolArray:
  Enabled: true

# Most readable form.
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
